---
- name: check if mongo installed
  remote_user: ubuntu
  become: true
  become_user: ubuntu
  stat: path=/usr/bin/mongo
  register: mongo_bin
  
- name: make sure mongod is stopped
  remote_user: ubuntu
  become: true
  become_user: ubuntu
  shell: sudo systemctl stop mongod
  when: mongo_bin.stat.exists == True
  ignore_errors: true

- name: remove mongodb package
  remote_user: ubuntu
  become: true
  become_user: root
  apt: name={{ item }} state=absent
  with_items:
    - mongodb-org-server
    - mongodb-org-mongos
    - mongodb-org-shell
    - mongodb-org-tools

- name: remove mongo related files (if needed)
  remote_user: ubuntu
  become: true
  become_user: root
  file: path={{ item }} state=absent
  with_items:
    - /etc/mongod.conf
    - /etc/mongodb-keyfile
    - /usr/bin/mongotop
    - /usr/bin/mongostat
    - /usr/bin/mongos
    - /usr/bin/mongorestore
    - /usr/bin/mongoperf
    - /usr/bin/mongooplog
    - /usr/bin/mongoimport
    - /usr/bin/mongofiles
    - /usr/bin/mongoexport
    - /usr/bin/mongodump
    - /usr/bin/mongo
    - /usr/bin/mongod
    - /etc/apt/sources.list.d/mongodb-org-3.6.list
  ignore_errors: true
 
- name: remove mongo directory
  remote_user: ubuntu
  become: true
  become_user: root
  file:
    path: "{{ hostvars[inventory_hostname]['db_directory'] }}"
    state: absent
