---
- name: MongoDB | Enable on Startup
  command: sudo systemctl enable mongod.service
  ignore_errors: true

- name: MongoDB | Insure deamon is running correctly
  shell: sudo systemctl restart mongod
  ignore_errors: true

